### ISSUE TITLE
laravel brcrypted generated password is not validating correctly

### ISSUE THREAD

**Issue by mistercorea** [olipayne/BcryptGenerator#3]
123456/$2y$10$3TZP9Y9zEafIDJ4jb3q1D.8531F2va1TVk0X/MU9AUF6tbp67aTRO
is generated from php 5.6 laravel 5.2 and when i check see if it is validates or not it is not matching 

Can you tell me what is wrong with it?

**Comment by guillaumegarcia13** [comment]
There are variants of BCrypt. 
Possibly, this GitHub repo is not able to check against your variant ($2y) of BCrypt (http://security.stackexchange.com/questions/20541/insecure-versions-of-crypt-hashes)
